version: 2

# template: &test-template

#   working_directory: /go/src/github.com/danielgg-coding/taiwanese-cuisine
#   steps:
#     - checkout
#     - run: go get -v -t -d ./...
#     - run: go test --coverpkg=./... -coverprofile=coverage.txt -covermode=atomic ./...
#     - run: bash <(curl -s https://codecov.io/bash)

jobs:
  
  build_and_test:
    docker:
      - image: circleci/golang:1.12
    steps:
      - checkout
      - setup_remote_docker:
          docker_layer_caching: true
      - run:
          name: Building Docker image
          command: |
            docker build -t danielgg/taiwanese-cuisine .
      - run:
          name: Unit testing
          command: |
            docker run danielgg/taiwanese-cuisine go test ./... --coverpkg=./...
  build_and_deploy:
    docker:
      - image: circleci/golang:1.12
    steps:
      - checkout
      - run: 
          name: Running unit tests
          command: |
      
workflows:
  version: 2
  cicd:
    jobs:
      - build_and_test
      - build_and_deploy: 
          requires: 
            - build_and_test
