version: 2

# template: &test-template

#   working_directory: /go/src/github.com/danielgg-coding/taiwanese-cuisine
#   steps:
#     - checkout
#     - run: go get -v -t -d ./...
#     - run: go test --coverpkg=./... -coverprofile=coverage.txt -covermode=atomic ./...
#     - run: bash <(curl -s https://codecov.io/bash)

jobs:
  build:
    docker:
      - image: circleci/golang:1.12
    steps:
      - checkout
      - run:
          name: Building Docker image
          command: |
            docker build -t danielgg/taiwanese-cuisine .

  test:
    steps:
      - run: 
        name: Running unit tests
        command: |
          docker run danielgg/taiwanese-cuisine go test ./... --coverpkg=./...
  
  # deploy:
  #   <<: *test-template
  #   docker:
  #     - image: circleci/golang:1.14
      
workflows:
  version: 2
  cicd:
    jobs:
      - build
      - test
