version: 2

template: &test-template

  working_directory: /go/src/github.com/danielgg-coding/taiwanese-cuisine
  steps:
    - checkout
    - run: go get -v -t -d ./...
    - run: go test --coverpkg=./... -coverprofile=coverage.txt -covermode=atomic ./...
    - run: bash <(curl -s https://codecov.io/bash)

jobs:
  test-1.12: &test-template
    <<: *test-template
    docker:
      - image: circleci/golang:1.12

  test-1.13:
    <<: *test-template
    docker:
      - image: circleci/golang:1.13
  
  test-1.14:
    <<: *test-template
    docker:
      - image: circleci/golang:1.14
      
workflows:
  version: 2
  test:
    jobs:
      - test-1.12
      - test-1.13
      - test-1.14
